import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { inter, manrope } from "@/app/ui/fonts";
import "./globals.css";
import Header from "@/app/ui/header/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin", "cyrillic"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Green Pato",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={`${manrope.className} antialiased text-base font-normal`}>
        <Header />
          <main className="pt-72 lg:pt-44">
            {children}
          </main>
        </body>
    </html>
  );
}
